import { makeStyles } from "@material-ui/core";

export default makeStyles({
  MainContainer: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
    width: "auto",
    alignItems: "center",
    padding: "0px",
    gap: "37.25rem",
  },
  Child1: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    padding: "0px",
    gap: "3.804rem",
  },
  NavbarMenus: {
    fontStyle: "normal",
    fontWeight: 500,
    fontSize: "17.6366px",
    lineHeight: "21px",
    color: "#FFFFFF",
    cursor: "pointer",
  },
  Child2: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    padding: "0px",
    gap: "29px",
  },
  Frame62: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    padding: "0px",
    gap: "7px",
  },
  Heading: {
    fontStyle: "normal",
    fontWeight: 500,
    fontSize: "17.6366px",
    lineHeight: "21px",
    color: "#FFFFFF",
  },
  Frame64: {
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
    padding: "0px",
    // gap: "7px",
  },
  Heading2: {
    marginTop: "1rem",
    fontStyle: "normal",
    fontWeight: 500,
    fontSize: "17.6366px",
    lineHeight: "21px",
    color: "#006AD4",
    cursor: "pointer",
  },
  Frame66: {
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
    padding: "0px",
    gap: "7px",
  },
  RegisterButton: {
    padding: "10px 20px",
    background: "#000000",
    borderRadius: "35px",
    fontStyle: "normal",
    fontWeight: 500,
    fontSize: "17.6366px",
    lineHeight: "21px",
    color: "#006AD4",
    cursor: "pointer",
  },
});
