import { makeStyles } from "@material-ui/core";

export default makeStyles({
  Frame121: {
    display: "flex",
    flexDirection: "column",
    // justifyContent: "center",
    alignItems: "center",
    padding: "20px 0px 10px",
    // gap: "10px",
    width: "299px",
    height: "100%",
    background: "#262626",
    position: "fixed",
    top: "0",
  },
  Frame126: {
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "flex-start",
    // paddingTop: "2rem",
    gap: "74px",
    width: "252px",
  },
  Frame123: {
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
    padding: "0px",
    gap: "10px",
  },
  Child01: {
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
    padding: "0px",
    gap: "32px",
    width: "inherit",
  },
  Frame122: {
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "flex-start",
    padding: "0px",
    gap: "74px",
    width: "inherit",
  },
  Frame124: {
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
    padding: "0px 0px 7px",
    width: "inherit",
  },
  Frame125: {
    border: "1px solid rgba(248, 250, 252, 0.2)",
    width: "inherit",
  },
  Frame31: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    padding: "12px 8px !important",
    gap: "95px",
    background: "#006AD5",
    borderRadius: "8px !important",
    width: "inherit",
    fontWeight: 510,
    fontSize: "16px",
    lineHeight: "19px",
    color: "#F8FAFC",
  },
  Frame21: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    padding: "12px 8px !important",
    gap: "95px",
    background: "#353739",
    borderRadius: "8px !important",
    width: "inherit",
    fontWeight: 510,
    fontSize: "16px",
    lineHeight: "19px",
    color: "#F8FAFC !important",
  },
  msgContainer: {
    display: "flex",
    alignItems: "center",
    fontWeight: 510,
    fontSize: "16px",
    lineHeight: "19px",
    color: "#F8FAFC",
  },
  optionsContainer: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    padding: "12px 8px",
    gap: "95px",
    width: "inherit",
    borderRadius: '8px',
    marginBottom: '0.1rem',
    cursor: 'pointer',
    '&:hover': {
      background: "#353739",
    }
  },
  optionWrapper: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    padding: "0px",
    gap: "4px",
  },
  optionText: {
    fontWeight: 510,
    fontSize: "16px",
    lineHeight: "19px",
    color: "#7F7F7F",
  },
  Frame128: {
    display: "flex",
    flexDirection: "column",
    alignItems: "flex-start",
    padding: "10px 0px 0px",
    gap: "220px",
    width: "252px",
  },
  Frame150: {
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
    padding: "0px",
    width: "inherit",
  },
  Frame151: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    padding: "0px 0px 30px",
    gap: "10px",
    width: "inherit",
    cursor: "pointer",
  },
  Frame152: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    padding: "12px",
    gap: "95px",
    width: "inherit",
    cursor: "pointer",
  },
  Frame153: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    padding: "0px",
    gap: "4px",
  },
  Frame154: {
    fontWeight: 510,
    fontSize: "16px",
    lineHeight: "19px",
    color: "#FFFFFF",
  },
  Frame155: {
    fontWeight: 400,
    fontSize: "14px",
    lineHeight: "17px",
    color: "#F8FAFC",
  },
  Frame156: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    padding: "12px 8px",
    gap: "95px",
    width: "inherit",
    borderRadius: '8px',
    marginBottom: '0.1rem',
    cursor: 'pointer',
    '&:hover': {
      background: "#353739",
    }
  },
  Frame157: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    padding: "0px",
    gap: "4px",
  },
  Frame158: {
    fontWeight: 510,
    fontSize: "16px",
    lineHeight: "19px",
    color: "#F8FAFC",
  },
  Frame159: {
    fontWeight: 400,
    fontSize: "14px",
    lineHeight: "17px",
    color: "#F8FAFC",
  },
  Frame162: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    padding: "0px",
  },
  Frame163: {
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "flex-start",
    padding: "0px 10px",
  },
  Frame164: {
    fontWeight: 510,
    fontSize: "16px",
    lineHeight: "19px",
    color: "#F8FAFC",
  },
  Frame165: {
    fontWeight: 400,
    fontSize: "14px",
    lineHeight: "17px",
    color: "#7F7F7F",
  },
  Frame166: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    padding: "0px",
  },
  profImage: {
    border: "1px solid rgba(255, 255, 255, 0.2)",
    width: "49px",
    height: "49px",
    borderRadius: "50%",
  },
});
