import HeroSection from "@/components/Login-HeroSection/HeroSection";
import SignupHeroSection from "@/components/Signup-HeroSection/SignupHerosection";
import { useAppSelector } from "@/store";
import type { NextPage } from "next";
import Head from "next/head";
import Navbar from "../src/components/navbar/Navbar";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  const { pageToggle } = useAppSelector((state) => state.Sign);
  return (
    <div className={styles.container}>
      <Head>
        <title>Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Navbar />
        {pageToggle ? (
          <SignupHeroSection />
        ) : (
          <HeroSection />
        )}
      </main>
    </div>
  );
};

export default Home;
