import type { NextPage } from "next";
import Head from "next/head";
import HeroSection from "../src/components/Login-HeroSection/HeroSection";
import Navbar from "../src/components/navbar/Navbar";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Navbar />
        <HeroSection />
      </main>
    </div>
  );
};

export default Home;
